name: Update and Build

on:
  schedule:
    - cron: "0 */1 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      job:
        description: "选择要执行的任务"
        required: true
        default: "update-and-build"
        type: choice
        options:
          - update-and-build
          - update-data
          - build

jobs:
  update-data:
    name: Update Data JSON
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.job == 'update-data' ||
      github.event.inputs.job == 'update-and-build'

    outputs:
      changed: ${{ steps.git-diff.outputs.changed }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests beautifulsoup4

      - name: Run update script
        run: python script/update-script.py

      - name: Check if data changed
        id: git-diff
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
          if git diff --quiet HEAD -- data; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.json data/info.json
          git commit -m "update: data.json, info.json"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --ff-only
          git push origin HEAD:main

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: update-data
    if: |
      (github.event_name != 'workflow_dispatch' && (needs.update-data.outputs.changed == 'true' || github.event_name == 'push')) ||
      github.event.inputs.job == 'build' ||
      github.event.inputs.job == 'update-and-build' ||
      github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Set build date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            stellatezero/anime-live-db:latest
            stellatezero/anime-live-db:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=stellatezero/anime-live-db:cache
          cache-to: type=registry,ref=stellatezero/anime-live-db:cache,mode=max
